### ISSUE TITLE
web3 is not a constructor

### ISSUE THREAD

**Issue by omago123** [omago123/ETH-TODO-LIST#1]
I am following the Building your First Blockchain tutorial
![web3 is not a constructor](https://user-images.githubusercontent.com/73014464/147120308-95088a64-221e-42c9-add7-6baa2567f67b.png)
And when I open my index.html page I get the following error on console

**Comment by omago123** [comment]
It was issue with MetaMask
With version 9.0.0 of the MetaMask browser extension, They  stopped providing the window.web3 API to websites. So I downloaded MetaMask Legacy Web3 Extension. and added it. Open again page It works fine
![metamask legacy](https://user-images.githubusercontent.com/73014464/147126419-b17d3cfb-ab55-466e-85a2-c3518c55b436.png)

**Comment by developerasun** [comment]
This is the right way to deal with legacy :) I would suggest to make a list that shows compatible or incompatible extensions towards your dapp in readme!
