### ISSUE TITLE
Transaction   no gas fee

### ISSUE THREAD

**Issue by omago123** [omago123/ETH-TODO-LIST#2]
![1](https://user-images.githubusercontent.com/73014464/147466237-00e366b2-b794-49f0-a3cd-c3af88d96544.png)

I made TodoList Dapp tutorial version.   When I try to add task,  it works.  transaction in ganache is completed. but  on metamask  nothing happened . I guess the dapp  isn't connected with metamask.  I couldn't find why yet.  so I keep trying to resolve this issue.

**Comment by developerasun** [comment]
check out this community below - maybe it's about gas fee limit, A transaction might have been made in ganache with fake ether(thus, reflected in fake account), meaning it is attempting to make the transaction but failed. 

https://community.metamask.io/

**Comment by omago123** [comment]
I figured out this issue by refering to the link . I followed manual,  so it worked fine.
https://medium.com/metamask/https-medium-com-metamask-breaking-change-injecting-web3-7722797916a


## before
![Inkedbefore_LI](https://user-images.githubusercontent.com/73014464/147542867-a51e92fe-97b9-41d5-8573-5dd95ad86168.jpg)

## after
![Inkedafter_LI](https://user-images.githubusercontent.com/73014464/147542858-2f255964-a95b-4ae3-9c10-a7e6fb4b363c.jpg)
